### PR TITLE
Course page responsiveness

### PR DESCRIPTION
**Pull request by MGafitescu**
Implemented mobile and tablet layouts for the Course page by modifying
the style.css file.

### CODE REVIEW

**Comment by MGafitescu** [comment]
Will edit the commit title, currently has a typo.

**Comment by bogsen** [comment]
We should make a separate pull request for README.md typos 🙂

**Review by bogsen — CHANGES_REQUESTED** [review]
Navbar commit from master is reverted, it shouldn't be

**Review by bogsen — DISMISSED** [review]
👍🏻👍🏻

**Review by bogsen — APPROVED** [review]
👍🏻👍🏻 2.0

**Pull request merged**
